// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqHEzgjsmaWrKTxO-NDan95tuG6jqXY18',
    appId: '1:853006238262:web:05acc679afadf4a5d98e97',
    messagingSenderId: '853006238262',
    projectId: 'bee---store',
    authDomain: 'bee---store.firebaseapp.com',
    storageBucket: 'bee---store.appspot.com',
    databaseURL: '',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_A7fh2sYNmyK41aB80O7OFYumH2YxiY',
    appId: '1:853006238262:android:0b5ecf4b12bdf254d98e97',
    messagingSenderId: '853006238262',
    projectId: 'bee---store',
    storageBucket: 'bee---store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPC31gS5x1LjRsZwbmdofIs-RY2AB6_jQ',
    appId: '1:853006238262:ios:335f53493966a273d98e97',
    messagingSenderId: '853006238262',
    projectId: 'bee---store',
    storageBucket: 'bee---store.appspot.com',
    iosBundleId: 'com.example.beestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPC31gS5x1LjRsZwbmdofIs-RY2AB6_jQ',
    appId: '1:853006238262:ios:0966b4cf1c743126d98e97',
    messagingSenderId: '853006238262',
    projectId: 'bee---store',
    storageBucket: 'bee---store.appspot.com',
    iosBundleId: 'com.example.beestore.RunnerTests',
  );
}
